name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop

jobs:
  # Nome da job.
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      # Executa os testes e gera o arquivo coverage.out que o sonar precisa
      - run: go test -coverprofile=coverage.out
      # Integração com o sonarcloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
